# What protocol to use when performing Git operations. Supported values: ssh, https.
git_protocol: ssh
# What editor glab should run when creating issues, merge requests, etc. This global config cannot be overridden by hostname.
editor:
# What browser glab should run when opening links. This global config cannot be overridden by hostname.
browser:
# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles
glamour_style: dark
# Allow glab to automatically check for updates and notify you when there are new updates.
check_update: true
# Last update check timestamp, used for checking when the last update check was performed.
last_update_check_timestamp: !!null 2025-04-18T08:22:26+05:30
# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.
display_hyperlinks: false
# Default GitLab hostname to use.
host: gitlab.com
# Set to true (1) to disable prompts, or false (0) to enable them.
no_prompt: false
# Configuration specific for GitLab instances.
hosts:
    gitlab.com:
        # What protocol to use to access the API endpoint. Supported values: http, https.
        api_protocol: https
        # Configure host for API endpoint. Defaults to the host itself.
        api_host: gitlab.com
        # Your GitLab access token. To get one, read https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
        token: !!null fb6a405e3885da840855cd498cba7e5b6f2be27c4f1caf34022bf15e729ec338
        is_oauth2: "true"
        oauth2_refresh_token: 5b8b0d72bb1cd9d516a6588cc4e83b9c44983da3b49c80acb749953a2a01ea9e
        oauth2_expiry_date: 18 Apr 25 10:23 IST
        oauth2_code_verifier: "CxmHmbKw8UqvAIuDQ82tx-WbfRNW2fUh-r_KmFpVXDs"
        git_protocol: https
        user: PriyangshuSarkar
