# Starship Configuration - Neatly Organized

# ──────────────────────────────
# Global Settings
# ──────────────────────────────
palette = "catppuccin_macchiato"

format="""
$directory\
[](fg:pink bg:base)\
$git_status\
[](fg:base bg:blue)\
$git_branch\
[](fg:blue)\
$line_break\
$line_break\
$character
"""

# $bun\
# $c\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $gleam\
# $golang\
# $haskell\
# $java\
# $julia\
# $kotlin\
# $lua\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $python\
# $raku\
# $rlang\
# $ruby\
# $rust\
# $scala\
# $swift\
# $zig\
# $package\

# ──────────────────────────────
# Core Segments
# ──────────────────────────────

[os]
disabled = true
format = "[$symbol ]($style)"
style = "bg:text fg:base"

[os.symbols]
AlmaLinux = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
Illumos = ""
Kali = ""
Linux = ""
Macos = ""
Manjaro = ""
Mint = "󰣭"
NixOS = ""
Nobara = ""
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Void = ""
Windows = ""


[shell]
disabled = true
format = "[$indicator]($style)"
style = "bg:text fg:base"
bash_indicator = "bash  "
zsh_indicator = "zsh  "
fish_indicator = "fish  "
powershell_indicator = "pwsh  "
pwsh_indicator = "pwsh  "
ion_indicator = "ion  "
nu_indicator = "nu 󰥭"
unknown_indicator = "shell "



[directory]
truncation_length = 4
style = "fg:mantle bg:pink"
format = "(fg:pink)[ $path ]($style)"

[git_branch]
format = '[[ $branch ](fg:base bg:blue)]($style)'
style = "bold bg:blue"

[git_status]
format ="([ 󰘬]($style)[\\([$all_status$ahead_behind]($style)\\) ]($style))"
style = "fg:text bg:base"

# ──────────────────────────────
# Language Runtimes
# ──────────────────────────────

[bun]
symbol = ""
style = "bg:surface1"
format = "[$symbol ($version) ](fg:yellow bg:base)"

[c]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:blue bg:base)"

[deno]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:text bg:base)"

[dotnet]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:blue bg:base)"

[elixir]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:mauve bg:base)"

[elm]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:green bg:base)"

[erlang]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:red bg:base)"

[gleam]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:lavender bg:base)"

[golang]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:sapphire bg:base)"

[haskell]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:mauve bg:base)"

[java]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:red bg:base)"

[julia]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:purple bg:base)"

[kotlin]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:lavender bg:base)"

[lua]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:blue bg:base)"

[nodejs]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:green bg:base)"

[ocaml]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:peach bg:base)"

[perl]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:teal bg:base)"

[php]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:purple bg:base)"

[python]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:yellow bg:base)"

[rlang]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:blue bg:base)"

[ruby]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:red bg:base)"

[rust]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:red bg:base)"

[scala]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:red bg:base)"

[swift]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:peach bg:base)"

[zig]
symbol = ""
style = "bg:base"
format = "[$symbol ($version) ](fg:yellow bg:base)"


# ──────────────────────────────
# Packages
# ──────────────────────────────

[package]
disabled = false
display_private = false
symbol = ""
style = "bg:base"
format = '[[$symbol ($version) ](fg:text bg:base)]($style)'


# ──────────────────────────────
# Utilities
# ──────────────────────────────

[docker_context]
disabled = true
detect_files = [ "docker-compose.yml", "docker-compose.yaml", "Dockerfile" ]
only_with_files = false
format = "[$symbol$context]($style)"
style = "bg:blue"
symbol = ""

[cmd_duration]
format = "[$duration]($style)"
style = "base bg:yellow"
min_time = 0
show_milliseconds = false
disabled = true

[memory_usage]
format = "[${ram}]($style)"
threshold = 0
style = "base bg:teal"
disabled = true

[time]
time_format = "%R"
format = '[[ $time](fg:mantle bg:flamingo)]($style)'
style = "bg:peach"
disabled = true

[fill]
symbol = " "

[battery]
format = "[$symbol$percentage]($style) "
disabled = true
[[battery.display]]
threshold = 100
style = "bold green"

# ──────────────────────────────
# UI / Visual
# ──────────────────────────────

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:lavender)'

# ──────────────────────────────
# Color Palettes
# ──────────────────────────────

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
