[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-mocha"

# dark = "gruvbox-dark"
# light = "gruvbox-dark"

[mgr]
border_symbol = "│"

[indicator]
padding = { open = "█", close = "█" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
