# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'                   # Catppuccin theme
set -g @plugin 'christoomey/vim-tmux-navigator'

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style 'slanted'

# --- General settings ---
# Enable mouse support (click to select, resize, scroll)
set -g mouse on

# Set window/pane indices to 1
set -g base-index 1
setw -g pane-base-index 1

# Set default terminal and enable true color
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Better splitting behavior
bind | split-window -h -c "#{pane_current_path}"    # horizontal split
bind - split-window -v -c "#{pane_current_path}"    # vertical split
set -g aggressive-resize on

# --- Status bar ---
set-option -g status-position top
set -g automatic-rename on
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cwd}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
